# fly.toml app configuration file generated for hedera-nextjs on 2023-05-19T16:46:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hedera-nextjs"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[env]
  TEST="hello"